#
# GeometricMagic allows players to draw redstone circles on the ground to do things such as teleport and transmute blocks.
# Copyright (C) 2012  Alec Cox (cakenggt), Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# TRANSMUTATION SECTION
transmutation:

    # What system to use for transmutation cost
    # Possible values: xp, vault (requires Vault)
    cost: xp

# VALUES SECTION (Values of blocks for transmutation)
values:
    0: 0
    1: 6
    2: 1
    3: 1
    4: 4
    5: 4
    6: 8
    7: 0
    8: 0
    9: 1
    10: 0
    11: 200
    12: 1
    13: 2
    14: 384
    15: 96
    16: 16
    17: 16
    18: 1
    19: 0
    20: 3
    21: 144
    22: 216
    23: 51
    24: 4
    25: 40
    26: 48
    27: 384
    28: 96
    29: 153
    30: 24
    31: 1
    32: 1
    33: 132
    34: 0
    35: 12
    36: 0
    37: 48
    38: 48
    39: 32
    40: 32
    41: 3456
    42: 864
    43: 8
    44: 4
    45: 24
    46: 484
    47: 96
    48: 4
    49: 192
    50: 4
    51: 1
    52: 0
    53: 6
    54: 32
    55: 8
    56: 1536
    57: 13824
    58: 16
    59: 4
    60: 1
    61: 32
    62: 32
    63: 0
    64: 24
    65: 7
    66: 36
    67: 6
    68: 0
    69: 6
    70: 12
    71: 576
    72: 8
    73: 32
    74: 32
    75: 10
    76: 10
    77: 12
    78: 1
    79: 4
    80: 4
    81: 8
    82: 16
    83: 8
    84: 1568
    85: 6
    86: 64
    87: 1
    88: 2
    89: 128
    90: 0
    91: 68
    92: 163
    93: 46
    94: 46
    95: 0
    96: 12
    97: 0
    98: 6
    99: 32
    100: 32
    101: 36
    102: 1
    103: 64
    104: 16
    105: 7
    106: 1
    107: 16
    108: 36
    109: 9
    110: 1
    111: 0
    112: 0
    113: 0
    114: 0
    115: 8
    116: 0
    117: 0
    118: 0
    119: 0
    120: 0
    121: 1
    122: 0
    123: 160
    124: 160
    125: 8
    126: 4
