#
# GeometricMagic allows players to draw redstone circles on the ground to do things such as teleport and transmute blocks.
# Copyright (C) 2012  Alec Cox (cakenggt), Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# TRANSMUTATION SECTION
transmutation:
    # Cool down time between transmutations in seconds
    cooldown: 10

    # What system to use for transmutation cost
    # Possible values: xp, vault (requires Vault)
    cost: xp

# SET CIRCLES SECTION
setcircles:
    # Cool down time between using set circles in seconds
    cooldown: 10

    # Limit augmentation size for set circles
    limitsize: 5

    # Repair Circle
    1133: []
    # Conversion Circle
    1222:
        # The cost of this circle in hunger
        cost: 1
    # Philosopher's Stone Circle
    1233:
        # The cost of this circle in hunger
        cost: 20
    # Boron Circle
    1234:
        # The cost of this circle in hunger
        cost: 1
        # The of redstone to drop
        amount: 1
    # Soul Circle
    2223:
        # The cost of this circle in hunger
        cost: 10
    # Homunculus Circle
    2224:
        # The cost of this circle in hunger
        cost: 10
    # Safe Teleportation Circle
    2244:
        # The cost of this circle in hunger
        cost: 1
    # Explosion Circle
    2333:
        # The cost of this circle in hunger
        # Formula: cost + circle size (can be augmented) / 2
        cost: 2
    # Fire Circle
    3334:
        # The cost of this circle in hunger
        cost: 5
        # The size of this circle in blocks cubed
        size: 3
    # Fire Explosion Circle
    3344:
        # The cost of this circle in hunger
        # Formula: cost + circle size (can be augmented) / 2
        cost: 10
        # The size of this circle in blocks cubed
        size: 3
    # Human Transmutation Circle
    3444:
        # The cost of this circle in hunger
        cost: 20
    # Bed Circle (0111)
    x111:
        # The cost of this circle in hunger
        cost: 16
    # Pig Circle (0044)
    x044:
        # The cost of this circle in hunger
        cost: 10
    # Sheep Circle (0144)
    x144:
        # The cost of this circle in hunger
        cost: 10
    # Cow Circle (0244)
    x244:
        # The cost of this circle in hunger
        cost: 10
    # Chicken Circle (0344)
    x344:
        # The cost of this circle in hunger
        cost: 10

# PHILOSOPHER'S STONE SECTION
philosopherstone:

    # The multiplier modifier of the philosopher's stone
    # Possible values: any integer
    # Formula: 1 / (2 to the power of (number of philosopher's stones in inventory) * modifier)
    modifier: 1

# VALUES SECTION (Values of blocks for transmutation)
values:
    0: 0
    1: 6
    2: 1
    3: 1
    4: 4
    5: 4
    6: 8
    7: 0
    8: 0
    9: 1
    10: 0
    11: 200
    12: 1
    13: 2
    14: 384
    15: 96
    16: 16
    17: 16
    18: 1
    19: 0
    20: 3
    21: 144
    22: 216
    23: 51
    24: 4
    25: 40
    26: 48
    27: 384
    28: 96
    29: 153
    30: 24
    31: 1
    32: 1
    33: 132
    34: 0
    35: 12
    36: 0
    37: 48
    38: 48
    39: 32
    40: 32
    41: 3456
    42: 864
    43: 8
    44: 4
    45: 24
    46: 484
    47: 96
    48: 4
    49: 192
    50: 4
    51: 1
    52: 0
    53: 6
    54: 32
    55: 8
    56: 1536
    57: 13824
    58: 16
    59: 4
    60: 1
    61: 32
    62: 32
    63: 0
    64: 24
    65: 7
    66: 36
    67: 6
    68: 0
    69: 6
    70: 12
    71: 576
    72: 8
    73: 32
    74: 32
    75: 10
    76: 10
    77: 12
    78: 1
    79: 4
    80: 4
    81: 8
    82: 16
    83: 8
    84: 1568
    85: 6
    86: 64
    87: 1
    88: 2
    89: 128
    90: 0
    91: 68
    92: 163
    93: 46
    94: 46
    95: 0
    96: 12
    97: 0
    98: 6
    99: 32
    100: 32
    101: 36
    102: 1
    103: 64
    104: 16
    105: 7
    106: 1
    107: 16
    108: 36
    109: 9
    110: 1
    111: 0
    112: 0
    113: 0
    114: 0
    115: 8
    116: 0
    117: 0
    118: 0
    119: 0
    120: 0
    121: 1
    122: 0
    123: 160
    124: 160
    125: 8
    126: 4
