#
# GeometricMagic allows players to draw redstone circles on the ground to do things such as teleport and transmute blocks.
# Copyright (C) 2012  Alec Cox (cakenggt), Andrew Stevanus (Hoot215) <hoot893@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

name: GeometricMagic
main: me.cakenggt.GeometricMagic.GeometricMagic
version: 2.4.1
author: cakenggt, Hoot215
softdepend: [Vault]
permissions:
    geometricmagic.*:
        description: Gives access to all circles and /setcircle
        default: false
        children:
            geometricmagic.standard: true
            geometricmagic.transmutation.*: true
    geometricmagic.standard:
        description: Gives access to standard circles and /setcircle
        default: true
        children:
            geometricmagic.teleportation: true
            geometricmagic.micro: true
            geometricmagic.transmutation.1: true
            geometricmagic.set: true
    geometricmagic.teleportation:
        description: Allows you to use teleportation circles
        default: false
    geometricmagic.micro:
        description: Allows you to use micro circles
        default: false
    geometricmagic.transmutation.*:
        description: Allows you to use all transmutation circles
        default: false
        children:
            geometricmagic.transmutation.1: true
            geometricmagic.transmutation.3: true
            geometricmagic.transmutation.4: true
            geometricmagic.transmutation.7: true
            geometricmagic.transmutation.9: true
    geometricmagic.transmutation.1:
        description: Allows you to use transmutation circles of size 1
        default: false
    geometricmagic.transmutation.3:
        description: Allows you to use transmutation circles of size 3
        default: false
    geometricmagic.transmutation.5:
        description: Allows you to use transmutation circles of size 5
        default: false
    geometricmagic.transmutation.7:
        description: Allows you to use transmutation circles of size 7
        default: false
    geometricmagic.transmutation.9:
        description: Allows you to use transmutation circles of size 9
        default: false
    geometricmagic.set:
        description: Allows you to use all set circles and /setcircle
        default: false
        children:
            circle.set.*: true
            circle.setcircle: true
    geometricmagic.setcircle:
        description: Allows you to use /setcircle
        default: false
    geometricmagic.set.*:
        description: Allows you to use all set circles
        default: false
        children:
            geometricmagic.set.1133: true
            geometricmagic.set.1222: true
            geometricmagic.set.1233: true
            geometricmagic.set.1234: true
            geometricmagic.set.2223: true
            geometricmagic.set.2224: true
            geometricmagic.set.2244: true
            geometricmagic.set.2333: true
            geometricmagic.set.3334: true
            geometricmagic.set.3344: true
            geometricmagic.set.3444: true
            geometricmagic.set.0111: true
            geometricmagic.set.0044: true
            geometricmagic.set.0144: true
            geometricmagic.set.0244: true
            geometricmagic.set.0344: true
    geometricmagic.set.1133:
        description: Allows you to use set circle 1133
        default: false
    geometricmagic.set.1222:
        description: Allows you to use set circle 1222
        default: false
    geometricmagic.set.1233:
        description: Allows you to use set circle 1233
        default: false
    geometricmagic.set.1234:
        description: Allows you to use set circle 1234
        default: false
    geometricmagic.set.2223:
        description: Allows you to use set circle 2223
        default: false
    geometricmagic.set.2224:
        description: Allows you to use set circle 2224
        default: false
    geometricmagic.set.2244:
        description: Allows you to use set circle 2244
        default: false
    geometricmagic.set.2333:
        description: Allows you to use set circle 2333
        default: false
    geometricmagic.set.3334:
        description: Allows you to use set circle 3334
        default: false
    geometricmagic.set.3344:
        description: Allows you to use set circle 1133
        default: false
    geometricmagic.set.3444:
        description: Allows you to use set circle 3444
        default: false
    geometricmagic.set.0111:
        description: Allows you to use set circle 0111
        default: false
    geometricmagic.set.0044:
        description: Allows you to use set circle 0044
        default: false
    geometricmagic.set.0144:
        description: Allows you to use set circle 0144
        default: false
    geometricmagic.set.0244:
        description: Allows you to use set circle 0244
        default: false
    geometricmagic.set.0344:
        description: Allows you to use set circle 0344
        default: false
commands:
  setcircle:
    description: This command sets a sacrifice's right-click circle.
    permission: geometricmagic.setcircle
    usage: /setcircle <####>
