name: GeometricMagic
main: me.kosannicholas.geometricmagic.GeometricMagicPlugin
version: 3.0.0
authors: [Gstayton]
database: true
commands:
  testEnergy:
  testUsername:
  addEnergy:
  getEnergyValue: